### PR TITLE
template: filter as associative array

### LINKED ISSUE #49: template: filter as associative array
| Q                | A
| ---------------- | -----
| Branch          | master, 1.x
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

The filters array available in the view should be associative, where the key is the configured filter's name. Thereby a specific filter can be accessed in the view more easily. BC is provided here since the template iterates over the filter array, regardless of the keys.

### PR DESCRIPTION
**Pull request by benwalch**
This PR resolves #49.

### CODE REVIEW

**Comment by solverat** [comment]
Thanks! Since this is a breaking change and will be merged in 3.0 (Pimcore 11 Support).

**Comment by solverat** [comment]
@benwalch could you please rebase this pr and also add some notes in upgrade.md (### Breaking Changes)

**Comment by benwalch** [comment]
@solverat  done, pls review

**Review by solverat — APPROVED** [review]

**Comment by solverat** [comment]
@benwalch perfect, thanks!

**Pull request merged**
